apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-magento
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
  maxShares: "3"
  cachingMode: None # ReadOnly cache is not available for premium SSD with maxShares>1
reclaimPolicy: Retain